[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://docs.rs/cursive"
exclude = ["doc/**", "assets/**", "examples/**"]
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "Readme.md"
repository = "https://github.com/gyscos/Cursive"
version = "0.8.3-alpha.0"
[badges.travis-ci]
repository = "gyscos/Cursive"

[dependencies]
enum-map = "0.2.24"
enumset = "0.3.3"
log = "0.4"
num = "0.1"
owning_ref = "0.3.3"
toml = "0.4"
unicode-segmentation = "1.0"
unicode-width = "0.1"
xi-unicode = "0.1.0"

[dependencies.maplit]
optional = true
version = "1.0.0"

[dependencies.bear-lib-terminal]
optional = true
version = "1.3.1"

[dependencies.chan]
optional = true
version = "0.1.18"

[dependencies.chan-signal]
optional = true
version = "0.3"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.91.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.15"

[dependencies.pulldown-cmark]
default-features = false
optional = true
version = "0.1.0"

[dependencies.termion]
optional = true
version = "1.5.0"

[dev-dependencies]
rand = "0.4"

[features]
blt-backend = ["bear-lib-terminal"]
default = ["ncurses-backend"]
markdown = ["pulldown-cmark"]
ncurses-backend = ["ncurses", "maplit"]
pancurses-backend = ["pancurses", "maplit"]
termion-backend = ["termion", "chan", "chan-signal"]

[lib]
name = "cursive"
